# Generated by Django 4.2.1 on 2023-06-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jour_de_naissance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
